modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/ochotonida/trofers/issues"
license="MIT"

[[mods]]
modId = "trofers"
version = "${file.jarVersion}"
displayName = "Trofers"
displayURL="https://www.curseforge.com/minecraft/mc-mods/trofers"
logoFile = "logo.png"
description = '''Adds trophies that can be customized through data packs'''

[[dependencies.trofers]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.18,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.trofers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"